#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # run functions

./Allclean
# copy mesh
cp -r ../refinement_3/constant/polyMesh/ constant/
# rename zero folder
cp -r 0.org 0
# map fields from previous refinement
runApplication mapFields -consistent -sourceTime latestTime ../hydro_steady_2/
# run simpleFoam
runApplication $(getApplication)
# post processing
touch post.foam

#------------------------------------------------------------------------------
