#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # run functions

./Allclean
# copy mesh
cp -r ../mesh/constant/polyMesh/ constant/
# copy flux field
latestTime=$(foamListTimes -latestTime -case ../hydro_steady/)
cp -r ../hydro_steady/$latestTime/phi 0/phi
# run solver
app=/home/bin/speciesFoam
runApplication $app
# extract training data
app=/home/bin/extractTrainingData
runApplication $app -maxDist 0.024

# post processing
touch post.foam

#------------------------------------------------------------------------------
