#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # run functions

./Allclean
# create symbolic link to PyTorch models
ln -sf /home/test_cases/pyTorchModels/bhaga_02_l16_u_tau_ts.pt velocityModel.pt
ln -sf /home/test_cases/pyTorchModels/bhaga_02_l16_inout_ts.pt radiusModel.pt
# copy mesh
cp -r ../refinement_1/constant/polyMesh/ constant/
# rename zero folder
cp -r 0.org 0
# map fields from previous refinement level
runApplication mapFields -consistent -sourceTime latestTime ../hydro_steady_0/
# run simpleFoam
runApplication $(getApplication)
# post processing
touch post.foam

#------------------------------------------------------------------------------
