#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # run functions

mkdir -p constant/triSurface
./Allclean

# Create a 2D wedge mesh of an axis-symmetric bubble using snappyHexMesh

## Create background mesh with blockMesh
runApplication blockMesh

## Create 3D mesh with snappyHexMesh
### Run snappyHexMesh
runApplication snappyHexMesh -overwrite
### Extrude upper patch to create a wedge
runApplication topoSet -dict system/topoSetDict.extrude
mv log.topoSet log.topoSet.extrude
runApplication createPatch -overwrite -dict system/createPatchDict.extrude
mv log.createPatch log.createPatch.extrude
runApplication extrudeMesh
runApplication collapseEdges -overwrite -collapseFaces
runApplication createPatch -overwrite -dict system/createPatchDict.rename
mv log.createPatch log.createPatch.rename

## Check mesh quality
runApplication checkMesh -constant
touch post.foam

#------------------------------------------------------------------------------
