#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # run functions

./Allclean
# copy mesh
cp -r ../mesh/constant/polyMesh/ constant/
# rename zero folder
cp -r 0.org 0
# run simpleFoam
runApplication $(getApplication)
# post processing
touch post.foam

#------------------------------------------------------------------------------
